// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: insertions.sql

package db

import (
	"context"
	"database/sql"
)

const createInsident = `-- name: CreateInsident :execresult


INSERT INTO incident (
    power_id,
    latitude,
    longtitude
) VALUES (?, ?, ?)
`

type CreateInsidentParams struct {
	PowerID    int32   `json:"power_id"`
	Latitude   float64 `json:"latitude"`
	Longtitude float64 `json:"longtitude"`
}

// noinspection SqlDialectInspectionForFile
// noinspection SqlNoDataSourceInspectionForFile
func (q *Queries) CreateInsident(ctx context.Context, arg CreateInsidentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInsident, arg.PowerID, arg.Latitude, arg.Longtitude)
}
