// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: insertions.sql

package db

import (
	"context"
	"database/sql"
)

const createInsident = `-- name: CreateInsident :execresult
INSERT INTO incident (
    longtitude,
    latitude,
    incident_type_id

) VALUES (?, ?, ?)
`

type CreateInsidentParams struct {
	Longtitude     float64 `json:"longtitude"`
	Latitude       float64 `json:"latitude"`
	IncidentTypeID int64   `json:"incident_type_id"`
}

func (q *Queries) CreateInsident(ctx context.Context, arg CreateInsidentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInsident, arg.Longtitude, arg.Latitude, arg.IncidentTypeID)
}

const createInsidentType = `-- name: CreateInsidentType :execresult


INSERT INTO incident_type (
    name
) VALUES (?)
`

// noinspection SqlDialectInspectionForFile
// noinspection SqlNoDataSourceInspectionForFile
func (q *Queries) CreateInsidentType(ctx context.Context, name string) (sql.Result, error) {
	return q.db.ExecContext(ctx, createInsidentType, name)
}
