// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Incident struct {
	ID             int64        `json:"id"`
	Latitude       float64      `json:"latitude"`
	Longtitude     float64      `json:"longtitude"`
	IncidentTypeID int64        `json:"incident_type_id"`
	CreatedAt      sql.NullTime `json:"created_at"`
	UpdatedAt      sql.NullTime `json:"updated_at"`
}

type IncidentType struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}
